In [1]:
import tensorflow as tf 

2024-03-26 14:25:17.917357: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-03-26 14:25:17.917599: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-03-26 14:25:18.073241: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-03-26 14:25:18.556950: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-03-26 14:25:22.569420: W tensorflow/compiler/tf2

### lets statty lrstning  the tensorflow more clrearly then evner 



In [23]:
### from this we got to knwo matrix / tendors with similar shapes can be multiplied and div 
#tensors are created by the tf.constant
#init a tf.constant 
a = tf.constant([1,2,3,4] , shape=(2,2))
b= tf.constant(3)
print(a+b , b-a , a*b , a/b)

tf.Tensor(
[[4 5]
 [6 7]], shape=(2, 2), dtype=int32) tf.Tensor(
[[ 2  1]
 [ 0 -1]], shape=(2, 2), dtype=int32) tf.Tensor(
[[ 3  6]
 [ 9 12]], shape=(2, 2), dtype=int32) tf.Tensor(
[[0.33333333 0.66666667]
 [1.         1.33333333]], shape=(2, 2), dtype=float64)


In [32]:
#specifying the datatype 
c = tf.constant([1.3 , 2.3 , 3.3 , 4.3 , 5.4 , 6.3 ,5.4, 3.4 ,.4, .6,1.3 , 2.3 , 3.3 , 4.3 , 5.4 , 6.3 ,5.4, 3.4 ] ,dtype = tf.float64 ,shape=(3,2,3))
c

<tf.Tensor: shape=(3, 2, 3), dtype=float64, numpy=
array([[[1.3, 2.3, 3.3],
        [4.3, 5.4, 6.3]],

       [[5.4, 3.4, 0.4],
        [0.6, 1.3, 2.3]],

       [[3.3, 4.3, 5.4],
        [6.3, 5.4, 3.4]]])>

In [34]:
##using the variable 

changeable = tf.Variable([1,2,3,4])
changeable[0].assign(3)

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([3, 2, 3, 4], dtype=int32)>

In [ ]:
#generating random tensors 
random_1 = tf.random.Generator.from_seed