In [2]:
import tensorflow as tf 

2024-03-27 10:59:58.945466: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-03-27 10:59:58.945683: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-03-27 10:59:59.146448: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-03-27 10:59:59.627091: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-03-27 11:00:04.660345: W tensorflow/compiler/tf2

### lets statty lrstning  the tensorflow more clrearly then evner 



In [3]:
### from this we got to knwo matrix / tendors with similar shapes can be multiplied and div 
#tensors are created by the tf.constant
#init a tf.constant 
a = tf.constant([1,2,3,4] , shape=(2,2))
b= tf.constant(3)
print(a+b , b-a , a*b , a/b)

tf.Tensor(
[[4 5]
 [6 7]], shape=(2, 2), dtype=int32) tf.Tensor(
[[ 2  1]
 [ 0 -1]], shape=(2, 2), dtype=int32) tf.Tensor(
[[ 3  6]
 [ 9 12]], shape=(2, 2), dtype=int32) tf.Tensor(
[[0.33333333 0.66666667]
 [1.         1.33333333]], shape=(2, 2), dtype=float64)


In [4]:
#specifying the datatype 
c = tf.constant([1.3 , 2.3 , 3.3 , 4.3 , 5.4 , 6.3 ,5.4, 3.4 ,.4, .6,1.3 , 2.3 , 3.3 , 4.3 , 5.4 , 6.3 ,5.4, 3.4 ] ,dtype = tf.float64 ,shape=(3,2,3))
c

<tf.Tensor: shape=(3, 2, 3), dtype=float64, numpy=
array([[[1.3, 2.3, 3.3],
        [4.3, 5.4, 6.3]],

       [[5.4, 3.4, 0.4],
        [0.6, 1.3, 2.3]],

       [[3.3, 4.3, 5.4],
        [6.3, 5.4, 3.4]]])>

In [5]:
##using the variable 

changeable = tf.Variable([1,2,3,4])
changeable[0].assign(3)

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([3, 2, 3, 4], dtype=int32)>

In [18]:
#generating random tensors 
random_1 = tf.random.Generator.from_seed(32)
random_1 = random_1.normal(shape=(2,2))
random_2 = tf.random.Generator.from_seed(32)
random_2 = random_2.normal(shape=(2,2))
random_2 ,random_1
random_1 == random_2

<tf.Tensor: shape=(2, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True]])>

In [25]:
random_3 =  tf.random.Generator.from_seed(32)
random_3_var = random_3.uniform(shape = (2,2) , minval=1 , maxval=10 , dtype=tf.int32)

In [26]:
random_3_var

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 9],
       [5, 1]], dtype=int32)>

In [40]:
### shuffleing the tensor when we want to shuffle the data 
not_shuffle = tf.random.uniform(shape = (3,2) , minval=1 , maxval=10)
not_shuffle

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[9.2879   , 7.8140306],
       [4.020514 , 2.4612727],
       [2.85181  , 5.463654 ]], dtype=float32)>

In [41]:
tf.random.shuffle(not_shuffle)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[2.85181  , 5.463654 ],
       [4.020514 , 2.4612727],
       [9.2879   , 7.8140306]], dtype=float32)>

In [47]:
#the shuffle becomes constant ranther then it diffres 
## performing the seed generation 
tf.random.set_seed(32)
tf.random.shuffle(not_shuffle)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[2.85181  , 5.463654 ],
       [9.2879   , 7.8140306],
       [4.020514 , 2.4612727]], dtype=float32)>

In [50]:
# the shuffle alwaays differs 
#without the global level seed 

tf.random.shuffle(not_shuffle , seed=32)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[2.85181  , 5.463654 ],
       [4.020514 , 2.4612727],
       [9.2879   , 7.8140306]], dtype=float32)>

In [ ]:
#creating the tensor from the numpy arrays 


In [57]:

ones=tf.ones([2,2,2,2])

In [56]:
#exploting the creation of tensors 


### getting info from tensors

In [58]:
ones.ndim

4

In [78]:
ones.shape

TensorShape([2, 2, 2, 2])

In [79]:
ones.dtype

tf.float32

In [83]:
#indexing the tensor 
ones[1,1,1].numpy()

array([1., 1.], dtype=float32)

In [81]:
size = tf.size(ones)
print(type(size))

<class 'tensorflow.python.framework.ops.EagerTensor'>


In [4]:
#specifying the datatype 
c = tf.constant([1.3 , 2.3 , 3.3 , 4.3 , 5.4 , 6.3 ,5.4, 3.4 ,.4, .6,1.3 , 2.3 , 3.3 , 4.3 , 5.4 , 6.3 ,5.4, 3.4 ] ,dtype = tf.float64 ,shape=(3,2,3))
c

<tf.Tensor: shape=(3, 2, 3), dtype=float64, numpy=
array([[[1.3, 2.3, 3.3],
        [4.3, 5.4, 6.3]],

       [[5.4, 3.4, 0.4],
        [0.6, 1.3, 2.3]],

       [[3.3, 4.3, 5.4],
        [6.3, 5.4, 3.4]]])>

In [82]:
ones[:,-1]

<tf.Tensor: shape=(2, 2, 2), dtype=float32, numpy=
array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]], dtype=float32)>

In [84]:
#addition subration  multiplication of the tensor 
### use the tf.math operations 

### matrix multiplication in tf 

In [120]:
tensor1 = tf.random.uniform(shape=(2,2),minval=1,maxval=10,dtype=tf.int32)
tensor2 = tf.random.uniform(shape=(2,2),minval=1,maxval=10,dtype=tf.int32)
tensor1 , tensor2

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[7, 3],
        [6, 9]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[2, 9],
        [2, 2]], dtype=int32)>)

In [121]:
matrix_mul = tf.matmul(tensor1 , tensor2)
matrix_mul

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 69],
       [30, 72]], dtype=int32)>

In [122]:
tensor1 @ tensor2 #for the matrix mulitplication 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 69],
       [30, 72]], dtype=int32)>

In [123]:
##multiplying the tensor of weird shape 
x = tf.random.uniform(shape = (3,2) , minval = 1,  maxval=10,dtype=tf.int32)
y = tf.random.uniform(shape = (3,2) , minval = 1,  maxval=10,dtype=tf.int32)
new_x =tf.reshape(x , shape=(2,3))

In [124]:
mat_mul = new_x@y
mat_mul

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[60, 83],
       [63, 59]], dtype=int32)>

In [125]:
a =tf.reshape(mat_mul , shape=(1,tf.size(mat_mul).numpy()))

In [126]:
## transpose of the matrix 
tf.transpose(mat_mul)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[60, 63],
       [83, 59]], dtype=int32)>

In [130]:
tf.tensordot(tf.transpose(x) , y , 0)

<tf.Tensor: shape=(2, 3, 3, 2), dtype=int32, numpy=
array([[[[24, 72],
         [32,  8],
         [64, 24]],

        [[ 6, 18],
         [ 8,  2],
         [16,  6]],

        [[24, 72],
         [32,  8],
         [64, 24]]],


       [[[15, 45],
         [20,  5],
         [40, 15]],

        [[15, 45],
         [20,  5],
         [40, 15]],

        [[ 6, 18],
         [ 8,  2],
         [16,  6]]]], dtype=int32)>