In [1]:
import tensorflow as tf 

2024-03-29 16:31:01.688861: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-03-29 16:31:01.689164: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-03-29 16:31:01.852765: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-03-29 16:31:02.304283: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-03-29 16:31:07.423445: W tensorflow/compiler/tf2

### lets statty lrstning  the tensorflow more clrearly then evner 



In [2]:
### from this we got to knwo matrix / tendors with similar shapes can be multiplied and div 
#tensors are created by the tf.constant
#init a tf.constant 
a = tf.constant([1,2,3,4] , shape=(2,2))
b= tf.constant(3)
print(a+b , b-a , a*b , a/b)

tf.Tensor(
[[4 5]
 [6 7]], shape=(2, 2), dtype=int32) tf.Tensor(
[[ 2  1]
 [ 0 -1]], shape=(2, 2), dtype=int32) tf.Tensor(
[[ 3  6]
 [ 9 12]], shape=(2, 2), dtype=int32) tf.Tensor(
[[0.33333333 0.66666667]
 [1.         1.33333333]], shape=(2, 2), dtype=float64)


In [3]:
#specifying the datatype 
c = tf.constant([1.3 , 2.3 , 3.3 , 4.3 , 5.4 , 6.3 ,5.4, 3.4 ,.4, .6,1.3 , 2.3 , 3.3 , 4.3 , 5.4 , 6.3 ,5.4, 3.4 ] ,dtype = tf.float64 ,shape=(3,2,3))
c

<tf.Tensor: shape=(3, 2, 3), dtype=float64, numpy=
array([[[1.3, 2.3, 3.3],
        [4.3, 5.4, 6.3]],

       [[5.4, 3.4, 0.4],
        [0.6, 1.3, 2.3]],

       [[3.3, 4.3, 5.4],
        [6.3, 5.4, 3.4]]])>

In [4]:
##using the variable 

changeable = tf.Variable([1,2,3,4])
changeable[0].assign(3)

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([3, 2, 3, 4], dtype=int32)>

In [5]:
#generating random tensors 
random_1 = tf.random.Generator.from_seed(32)
random_1 = random_1.normal(shape=(2,2))
random_2 = tf.random.Generator.from_seed(32)
random_2 = random_2.normal(shape=(2,2))
random_2 ,random_1
random_1 == random_2

<tf.Tensor: shape=(2, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True]])>

In [6]:
random_3 =  tf.random.Generator.from_seed(32)
random_3_var = random_3.uniform(shape = (2,2) , minval=1 , maxval=10 , dtype=tf.int32)

In [7]:
random_3_var

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 9],
       [5, 1]], dtype=int32)>

In [8]:
### shuffleing the tensor when we want to shuffle the data 
not_shuffle = tf.random.uniform(shape = (3,2) , minval=1 , maxval=10)
not_shuffle

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[4.5893555, 4.3413415],
       [8.631168 , 4.154174 ],
       [8.364477 , 7.8290963]], dtype=float32)>

In [9]:
tf.random.shuffle(not_shuffle)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[8.364477 , 7.8290963],
       [8.631168 , 4.154174 ],
       [4.5893555, 4.3413415]], dtype=float32)>

In [10]:
#the shuffle becomes constant ranther then it diffres 
## performing the seed generation 
tf.random.set_seed(32)
tf.random.shuffle(not_shuffle)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[8.364477 , 7.8290963],
       [4.5893555, 4.3413415],
       [8.631168 , 4.154174 ]], dtype=float32)>

In [11]:
# the shuffle alwaays differs 
#without the global level seed 

tf.random.shuffle(not_shuffle , seed=32)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[8.364477 , 7.8290963],
       [8.631168 , 4.154174 ],
       [4.5893555, 4.3413415]], dtype=float32)>

In [12]:
#creating the tensor from the numpy arrays 


In [13]:

ones=tf.ones([2,2,2,2])

In [14]:
#exploting the creation of tensors 


### getting info from tensors

In [15]:
ones.ndim

4

In [16]:
ones.shape

TensorShape([2, 2, 2, 2])

In [17]:
ones.dtype

tf.float32

In [18]:
#indexing the tensor 
ones[1,1,1].numpy()

array([1., 1.], dtype=float32)

In [19]:
size = tf.size(ones)
print(type(size))

<class 'tensorflow.python.framework.ops.EagerTensor'>


In [20]:
#specifying the datatype 
c = tf.constant([1.3 , 2.3 , 3.3 , 4.3 , 5.4 , 6.3 ,5.4, 3.4 ,.4, .6,1.3 , 2.3 , 3.3 , 4.3 , 5.4 , 6.3 ,5.4, 3.4 ] ,dtype = tf.float64 ,shape=(3,2,3))
c

<tf.Tensor: shape=(3, 2, 3), dtype=float64, numpy=
array([[[1.3, 2.3, 3.3],
        [4.3, 5.4, 6.3]],

       [[5.4, 3.4, 0.4],
        [0.6, 1.3, 2.3]],

       [[3.3, 4.3, 5.4],
        [6.3, 5.4, 3.4]]])>

In [21]:
ones[:,-1]

<tf.Tensor: shape=(2, 2, 2), dtype=float32, numpy=
array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]], dtype=float32)>

In [22]:
#addition subration  multiplication of the tensor 
### use the tf.math operations 

### matrix multiplication in tf 

In [23]:
tensor1 = tf.random.uniform(shape=(2,2),minval=1,maxval=10,dtype=tf.int32)
tensor2 = tf.random.uniform(shape=(2,2),minval=1,maxval=10,dtype=tf.int32)
tensor1 , tensor2

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[9, 5],
        [4, 3]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[8, 2],
        [6, 9]], dtype=int32)>)

In [24]:
matrix_mul = tf.matmul(tensor1 , tensor2)
matrix_mul

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[102,  63],
       [ 50,  35]], dtype=int32)>

In [25]:
tensor1 @ tensor2 #for the matrix mulitplication 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[102,  63],
       [ 50,  35]], dtype=int32)>

In [26]:
##multiplying the tensor of weird shape 
x = tf.random.uniform(shape = (3,2) , minval = 1,  maxval=10,dtype=tf.int32)
y = tf.random.uniform(shape = (3,2) , minval = 1,  maxval=10,dtype=tf.int32)
new_x =tf.reshape(x , shape=(2,3))

In [27]:
mat_mul = new_x@y
mat_mul

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 80, 102],
       [ 88, 102]], dtype=int32)>

In [28]:
a =tf.reshape(mat_mul , shape=(1,tf.size(mat_mul).numpy()))

In [29]:
## transpose of the matrix 
tf.transpose(mat_mul)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 80,  88],
       [102, 102]], dtype=int32)>

In [30]:
tf.tensordot(tf.transpose(x) , y , 0)

<tf.Tensor: shape=(2, 3, 3, 2), dtype=int32, numpy=
array([[[[32, 48],
         [48, 64],
         [72, 56]],

        [[ 8, 12],
         [12, 16],
         [18, 14]],

        [[16, 24],
         [24, 32],
         [36, 28]]],


       [[[20, 30],
         [30, 40],
         [45, 35]],

        [[28, 42],
         [42, 56],
         [63, 49]],

        [[16, 24],
         [24, 32],
         [36, 28]]]], dtype=int32)>

In [33]:
#chamgomh the dt of the tensors 
b = tf.constant(3.0)
b_changes = tf.cast(b , dtype = tf.int16)

In [35]:
b_changes.numpy()

3

In [36]:
#now for the matrix 
c = tf.random.normal(shape=(3,3,2),dtype=tf.float32)
c_changes = tf.cast(c , dtype= tf.int16)

In [38]:

c ,c_changes


(<tf.Tensor: shape=(3, 3, 2), dtype=float32, numpy=
 array([[[-0.24772178, -0.2634273 ],
         [-1.2853099 , -1.0109924 ],
         [ 0.44478774,  0.15881398]],
 
        [[-0.5393688 ,  0.5953197 ],
         [-1.9483345 , -0.12836277],
         [ 0.60093546, -0.27676448]],
 
        [[-0.51321167,  0.8389473 ],
         [ 0.17655647,  1.4178522 ],
         [ 1.4637741 , -0.7697929 ]]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3, 2), dtype=int16, numpy=
 array([[[ 0,  0],
         [-1, -1],
         [ 0,  0]],
 
        [[ 0,  0],
         [-1,  0],
         [ 0,  0]],
 
        [[ 0,  0],
         [ 0,  1],
         [ 1,  0]]], dtype=int16)>)

### agregating the tensors 

aggregating tensors means to condensing the multple tensors to the smaller ones 

In [44]:
# for the absolute val 
a = tf.random.uniform(shape=(3,3) , minval=-10 , maxval=10 , dtype=tf.int32)
a_abs = tf.abs(a)

In [45]:
a,a_abs

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[  6,  -8,   7],
        [ -7,   8,  -3],
        [ -6, -10,   1]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[ 6,  8,  7],
        [ 7,  8,  3],
        [ 6, 10,  1]], dtype=int32)>)

In [47]:
#second way of making a tensor of
import numpy as np 
x = tf.constant(np.random.randint(0,100 , size = 50))
x_abs = tf.abs(x)

In [57]:
#find the min among the tensor 
tf.reduce_min(a),tf.reduce_max(a), tf.reduce_mean(a)

(<tf.Tensor: shape=(), dtype=int32, numpy=-10>,
 <tf.Tensor: shape=(), dtype=int32, numpy=8>,
 <tf.Tensor: shape=(), dtype=int32, numpy=-1>)